[package]
name = "acure-base"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "acure"
crate-type = ["cdylib"]

[dependencies]
acure = { path = "../../", version = "0.0.1" }